version: '2'
services:
  mapas:
    env_file:
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: /var/www/dev/start.sh
    ports:
      - "80:80"
    volumes:
      - ./.env:/.env      
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # scripts principais
      - ../docker/entrypoint.sh:/entrypoint.sh
      - ../docker/jobs-cron.sh:/jobs-cron.sh
      - ../docker/recreate-pending-pcache-cron.sh:/recreate-pending-pcache-cron.sh

      - ../composer.json:/var/www/composer.json
      - ../composer.lock:/var/www/composer.lock

      - ../config:/var/www/config
      - ../public:/var/www/html
      - ../scripts:/var/www/scripts
      - ../src:/var/www/src
      - ../var:/var/www/var

      - ../docker/development/router.php:/var/www/router.php

      - ./config.d:/var/www/config/config.d

      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/var/private-files
      
      - ../docker/development/router.php:/var/www/dev/router.php


    links:
      - redis
      - sessions
#     - db
      
    environment:
      - REDIRECT_404_ASSETS_TO=

      - BUILD_ASSETS=0
      - PENDING_PCACHE_RECREATION_INTERVAL=5
      - JOBS_INTERVAL=5
      - REDIS_CACHE=redis
      
      - SESSIONS_SAVE_PATH=tcp://sessions:6379

    depends_on:
      - redis
      - sessions
#     - mailhog
#     - db

    stdin_open: true
    tty: true
    
  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru  

  sessions:
    image: redis:6
    restart: unless-stopped
    command: --maxmemory 128Mb --maxmemory-policy allkeys-lru
    volumes:
      - ./docker-data/sessions:/data

############################################################################################################
# Em caso de ativar este serviço 'mailhog', lembre de definir as seguintes variaveis no arquivo '.env':    #
#  MAIL_TRANSPORT=smtp://mailhog:1025 => seguindo o padrão 'protocolo://servidor:porta'                    #
#  MAIL_FROM=sysadmin@localhost => este é o remetente que aparecerá nas mensagens enviadas pelo sistema e  #
#                                   pode ser alterado conforme interesse e conveniência.                   #
############################################################################################################
# mailhog: # Detalhes sobre a configuração deste serviço 'MailHog' disponível em <https://hub.docker.com/r/mailhog/mailhog/>.
#   image: mailhog/mailhog
#   ports:
#     - "8025:8025"
#
############################################################################################################
# Em caso de ativar este serviço 'db', lembre de definir/ajustar as seguintes variaveis no arquivo '.env': #
#  DB_HOST=servidor => nome do servidor de banco de dados                                                  #
#  DB_NAME=nomedobanco => nome do banco de dados                                                           #
#  DB_USER=nomedousuario => usuario de acesso ao banco de dados                                            #
#  DB_PASS=******* => senha de acesso ao banco de dados                                                    #
#  DB_VERSION=N => numero da verso do servidor de banco de dados                                           #
############################################################################################################
# db: # Detalhes sobre configuração deste serviço 'Postgres' disponível em <https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/>.
#   image: postgis/postgis:14-master
#   environment:
#     - POSTGRES_PASSWORD=mapas
#     - POSTGRES_USER=mapas
#     - POSTGRES_DB=mapas
#   ports:
#     - "5432:5432"
#   volumes:
#     - ./docker-data/postgres:/var/lib/postgresql/data
#     - ./db:/docker-entrypoint-initdb.d
